django_plastic_tickets/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.tickets_index_view, name='plastic_tickets_index'),
    path('new/', views.new_ticket_view, name='plastic_tickets_new'),
    path('list/', views.ticket_list_view, name='plastic_tickets_list'),
    path('new/<active_file>', views.new_ticket_view,
         name='plastic_tickets_new_with_file'),
    path('<id>/', views.ticket_view, name='plastic_tickets_ticket'),
    path('<id>/files/<filename>', views.file_view,
         name='plastic_tickets_file'),
]

django_plastic_tickets/models.py
import textwrap
from pathlib import Path
from typing import List

import django.urls
import markdown
from django_plastic_tickets.ral_colors import ral_colors
from django.conf import settings
from django.contrib.auth.models import User
from django.db import models
from django.utils.translation import gettext
from django.core.exceptions import ValidationError
from django.db.models import F
from django.db.models import Q
from django.utils import translation


def validate_ral_number(val):
    if val != 0 and val not in ral_colors:
        raise ValidationError(gettext(
            'This is not a valid RAL classic color number'))


def localized_color_name(ral_number):
    if ral_number == 0:
        return gettext("No Color")
    else:
        lang = translation.get_language()
        return ral_colors[ral_number][lang]


def build_url(path: str) -> str:
    return settings.URL_SCHEME + settings.HOSTNAME + path


class DescribedModel(models.Model):
    name = models.TextField()
    markdown_description = models.TextField(
        help_text=gettext('The markdown-formatted description'))

    class Meta:
        abstract = True

    def render_description(self) -> str:
        # TODO: Cache html
        return markdown.markdown(self.markdown_description)

    def to_dict(self) -> dict:
        return {'name': self.name,
                'display_name': self.name,
                'description': self.render_description()}

    def __str__(self) -> str:
        return self.name


class ProductionMethod(DescribedModel):
    pass


class MaterialType(DescribedModel):
    production_method = models.ForeignKey(ProductionMethod,
                                          on_delete=models.CASCADE)
    density = models.FloatField(
        help_text=gettext('Density in g/cm^3'),
        blank=True, null=True)

    def __str__(self) -> str:
        return f'{self.name} ({self.production_method})'


class Manufacturer(DescribedModel):
    url = models.URLField(blank=True, null=True)


class MaterialProperty(DescribedModel):
    class Meta:
        verbose_name_plural = "Material properties"


class Material(models.Model):
    """Base class for a physical material"""
    type = models.ForeignKey(MaterialType, on_delete=models.CASCADE)
    manufacturer = models.ForeignKey(Manufacturer, on_delete=models.CASCADE)
    name = models.TextField(blank=True, null=True)
    url = models.URLField(blank=True, null=True)
    ral_color_number = models.PositiveIntegerField(
        validators=[validate_ral_number],
        help_text=gettext('A RAL classic color number, '
                          'or 0 if a color can not be specified'))
    properties = models.ManyToManyField(MaterialProperty, blank=True)

    def get_display_name(self) -> str:
        if self.ral_color_number != 0:
            return (f'{self.get_color_name()} '
                    f'(RAL {self.ral_color_number})')
        else:
            return gettext("None")

    def get_disp_list_name(self) -> str:
        props = list(self.properties.all())
        props.sort(key=lambda t: t.name)
        if props:
            return props, (self.type.name + " + " +
                           ", ".join(prop.name for prop in props))
        else:
            return props, self.type.name

    def get_color_name(self) -> str:
        return localized_color_name(self.ral_color_number)

    def _str_inner(self) -> str:
        res = (f"{self.manufacturer.name}, "
               f"{self.type.name}")
        if self.ral_color_number != 0:
            res += ", " + self.get_color_name()
        for prop in self.properties.all():
            res += f", {prop.name}"
        return res

    def __str__(self) -> str:
        if self.name is not None and self.name != "":
            return f"{self.name} ({self._str_inner()})"
        else:
            return self._str_inner()


class ResinMaterial(Material):
    pass


class FilamentMaterial(Material):
    nozzle_temp = models.FloatField(blank=True, null=True, help_text=gettext(
        "Optimal nozzle temperature"))
    bed_temp = models.FloatField(blank=True, null=True, help_text=gettext(
        "Optimal bed temperature"))
    diameter = models.FloatField(blank=True, null=True, default=1.75,
                                 help_text=gettext("Diameter of the filament"))


class MaterialPackage(models.Model):
    """A spool, bottle or any other material package"""
    manufacturer = models.ForeignKey(Manufacturer, blank=True, null=True,
                                     on_delete=models.CASCADE)
    empty_weight = models.FloatField(blank=True, null=True, help_text=gettext(
        "Weight of the empty package in gram"))
    usual_capacity = \
        models.FloatField(blank=True, null=True, help_text=gettext(
            "Amount of material in gram, "
            "which is usually shipped with this package"))
    model = models.TextField(blank=True, null=True, help_text=gettext(
        "Model name of the spool, as defined by the manufacturer"))
    appearance = models.TextField(help_text=gettext(
        "Short description of the appearance of this package"))

    def __str__(self) -> str:
        res = ""
        if self.manufacturer is not None:
            res = f"{self.manufacturer}, "
        if self.usual_capacity is not None and self.usual_capacity > 0:
            res += f"{self.usual_capacity} g, "
        if self.model is not None and self.model.strip() != "":
            return res + self.model
        else:
            return res + self.appearance


class MaterialStock(models.Model):
    """Base class for a material that is/was in stock"""
    material = models.ForeignKey(Material, on_delete=models.CASCADE)
    package = models.ForeignKey(MaterialPackage, on_delete=models.CASCADE)
    label = models.PositiveIntegerField(
        help_text=gettext('The internal label to identify the material'),
        unique=True)
    initial_material_weight = models.FloatField(help_text=gettext(
        'Initial weight of the material in gram, ' +
        'not including the weight of the package'))
    current_weight = models.FloatField(help_text=gettext(
        'Current weight of the material in gram, ' +
        'including the weight of the package'))
    price = models.FloatField(blank=True, null=True, help_text=gettext(
        'Total price, including the package.'))
    owner = models.ForeignKey(
        User, on_delete=models.CASCADE, help_text=gettext(
            'The owner of the material'))
    usage_comment = models.TextField(
        blank=True, null=True, help_text=gettext(
            'Hints about how to use this material'))

    def to_dict(self) -> dict:
        return {"display_name": self.material.get_display_name(),
                "name": str(self.label)}

    def __str__(self) -> str:
        remaining_weight = "?"
        if self.package.empty_weight is not None:
            remaining = self.current_weight - self.package.empty_weight
            if remaining > 0:
                remaining_weight = f"{remaining:.0f} g"
            else:
                remaining_weight = "empty"
        return f'{self.label}: {self.material}: {remaining_weight}'


class Ticket(models.Model):

    class TicketState(models.TextChoices):
        OPEN = 'OP', gettext('Open')
        REJECTED = 'RE', gettext('Rejected')
        DONE = 'DO', gettext('Done')

    message = models.TextField(blank=True)
    state = models.CharField(
        max_length=2,
        choices=TicketState.choices,
        default=TicketState.OPEN)
    assignee = models.ForeignKey(
        User, blank=True, null=True,
        on_delete=models.CASCADE, help_text=gettext(
            'The staff member who works on the ticket'))

    def get_url(self):
        return build_url(django.urls.reverse(
            'plastic_tickets_ticket', kwargs={'id': self.id}
        ))

    def get_message_row_count(self, cols=77) -> int:
        sum = 0
        for line in self.message.splitlines():
            sum += max(1, len(textwrap.wrap(line, cols)))
        return sum + 0

    def badge(self) -> str:
        if self.state == "OP":
            if self.assignee is None:
                return "UN"
            else:
                return "PR"
        else:
            return self.state

    def __str__(self) -> str:
        return f"#{self.id}: {self.state}"


class PrintConfig(models.Model):
    file = models.FilePathField()
    count = models.PositiveIntegerField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    material_stocks = models.ManyToManyField(MaterialStock)
    ticket = models.ForeignKey(Ticket, on_delete=models.CASCADE, null=True)

    def get_first_material(self) -> MaterialStock:
        return next(iter(self.material_stocks.all())).material

    def get_color_name(self) -> str:
        return self.get_first_material().get_display_name()

    def get_material_type_name(self) -> str:
        return self.get_first_material().get_disp_list_name()[1]

    def get_file_name(self) -> str:
        return Path(self.file).name

    def get_file_url(self):
        return build_url(django.urls.reverse(
            'plastic_tickets_file', kwargs={
                'id': self.ticket.id, 'filename': self.get_file_name()
            }))

    def get_material_stock_list(self) -> str:
        return ", ".join(str(s.label) for s in self.material_stocks.all())

    def __str__(self) -> str:
        if self.ticket is None:
            tstr = "?"
        else:
            tstr = str(self.ticket.pk)
        return (f'#{tstr}: {self.count}, "{self.file}",'
                f'{self.get_material_stock_list()}')


def get_material_type_options(stocks: [MaterialStock]) -> List[dict]:
    res = {}
    for stock in stocks:
        mat = stock.material
        props, disp_list = mat.get_disp_list_name()
        try:
            colors = res[disp_list]["material_colors"]
            try:
                colors[mat.ral_color_number]["name"] += "," + str(stock.label)

django_plastic_tickets/templates/plastic_tickets/new_ticket.html
{% extends 'base.html' %}

{% load i18n %}
{% load django_bootstrap_breadcrumbs %}

{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb 'Plastic tickets' 'plastic_tickets_index' %}
    {% breadcrumb 'New' 'plastic_tickets_new' %}
{% endblock %}

{% block content %}
    {{ block.super }}

    {% if not files %}
        {% include 'plastic_tickets/new_ticket_start.html' %}
    {% else %}
        {% include 'plastic_tickets/new_ticket_file_upload.html' %}

        <ul class="nav nav-tabs">
            {% for file in files %}
                <li class="nav-item">
                    <a class="nav-link {% if file.name == active_file.name %} active{% endif %}"
                       href="{{ file.name }}">{{ file.name }}
                        {% if file in configured_files %} ✓ {% endif %}
                    </a>
                </li>
            {% endfor %}
        </ul>

        <div class="card">
            <div class="card-body">
                {% include 'plastic_tickets/new_ticket_file_form.html' %}
            </div>
        </div>

        {% if fully_configured %}
            {% include 'plastic_tickets/new_ticket_submit.html' %}
        {% else %}
            {% blocktrans %}
                Configure all files to submit the ticket.
            {% endblocktrans %}
        {% endif %}
    {% endif %}
{% endblock %}

django_plastic_tickets/templates/plastic_tickets/new_ticket_file_form.html
{% load i18n %}

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}

    <div class="form-group">
        <h4>{% trans 'Basic information' %}</h4>
        <small>
            {% blocktrans %}
                The basic information you <b>have to</b> choose yourself.
            {% endblocktrans %}
        </small>
    </div>

    <div class="form-group">
        <label for="count">
            {% trans 'Count' %}:
        </label>
        <label aria-describedby="count_desc">
            <input class="form-control" type="number" id="count" min="1"
                   name="file_count" value="{{count}}">
        </label>
        <small id="count_desc" class="form-text">
            {% blocktrans %}
                How many times do you want to have this model printed?
            {% endblocktrans %}
        </small>
    </div>

    <div class="form-group">
        <label for="production_method">
            {% trans 'Production method' %}:
        </label>
        <label>
            <select class="select2-dropdown" id="production_method"
                    name="production_method">
            </select>
        </label>
        <small id="production_method_desc" class="form-text">
            {% blocktrans %}
                Which production method should be used?
            {% endblocktrans %}
        </small>
        <small class="form-text">
            {% blocktrans %}
                Here is a quick description of your current selection:
            {% endblocktrans %}
        </small>
        <small id="production_method_summary">
            {% blocktrans %}
                Placeholder: Please enable JavaScript!
            {% endblocktrans %}
        </small>
    </div>

    <div class="form-group">
        <label for="material_type">
            {% trans 'Material type' %}:
        </label>
        <label>
            <select class="select2-dropdown" id="material_type"
                    name="material_type">
            </select>
        </label>
        <small id="material_type_desc" class="form-text">
            {% blocktrans %}
                Which material should be used?
            {% endblocktrans %}
        </small>
        <small class="form-text">
            {% blocktrans %}
                Here is a quick description of your current selection:
            {% endblocktrans %}
        </small>
        <small id="material_type_summary">
            {% blocktrans %}
                Placeholder: Please enable JavaScript!
            {% endblocktrans %}
        </small>
    </div>

    <div class="form-group">
        <label for="material_color">
            {% trans "Material color" %}:
        </label>
        <label>
            <select class="select2-dropdown" id="material_color"
                    name="material_color">
            </select>
        </label>
        <small id="material_type_desc" class="form-text">
            {% blocktrans %}
                Which color should the material have?
            {% endblocktrans %}
        </small>
    </div>

    {% comment %}
    TODO for later
    <div class="form-group">
        <h4>Advanced information</h4>
        <small>
            {% blocktrans %}
                The advanced information you <em>can</em> choose yourself.
                <br>
                If not specified, we will take care of this.
            {% endblocktrans %}
        </small>
    </div>
    {% endcomment %}

    <button type="submit" class="btn btn-primary"
            name="config_form">{% trans "Save" %}</button>
    <button type="button" class="btn btn-secondary" id="reset-btn">{% trans "Reset" %}</button>
</form>

<script type="text/javascript">
    const tree = {{js_data|safe}};

    let pm = document.getElementById('production_method');
    let mt = document.getElementById('material_type');
    let mc = document.getElementById('material_color');

    let pm_desc = document.getElementById('production_method_summary');
    let mt_desc = document.getElementById('material_type_summary');

    let update_mt_options = function () {
        const pm_index = pm.selectedIndex;
        mt.options.length = 0;
        for (let material in tree[pm_index].material_types) {
            let o = tree[pm_index].material_types[material];
            mt.options.add(new Option(o.display_name, o.name));
        }
    }

    let update_mc_options = function () {
        const pm_index = pm.selectedIndex;
        const mt_index = mt.selectedIndex;
        mc.options.length = 0;
        for (let color in
            tree[pm_index].material_types[mt_index].material_colors) {
            let o = tree[pm_index]
                .material_types[mt_index]
                .material_colors[color];
            mc.options.add(new Option(o.display_name, o.name));
        }
    }

    let update_descriptions = function () {
        pm_desc.innerHTML = tree[pm.selectedIndex].description;
        mt_desc.innerHTML = tree[pm.selectedIndex]
            .material_types[mt.selectedIndex].description;
    }

    pm.onchange = function () {
        update_mt_options();
        update_descriptions();
    };

    mt.onchange = function () {
        update_mc_options();
        update_descriptions();
    };

    // Initial data
    for (const method in tree) {
        let o = tree[method];
        pm.options.add(new Option(o.display_name, o.name));
    }

    let reset = function () {
        {% if selected_pm %}
        pm.value = '{{selected_pm}}';
        {% else %}
        pm.selectedIndex = 0;
        {% endif %}
        update_mt_options();
        {% if selected_mat_type %}
        mt.value = '{{selected_mat_type}}';
        {% endif %}
        update_mc_options();
        {% if selected_color %}
        mc.value = '{{selected_color}}';
        {% endif %}
        update_descriptions();
   }
   document.getElementById("reset-btn").onclick = reset;
   reset();
</script>

django_plastic_tickets/templates/plastic_tickets/new_ticket_file_upload.html
{% load i18n %}
<div>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            <label>
                {% trans 'Upload files' %}:
                <input name="file[]" type="file" multiple>
            </label>
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-primary" name="file_upload">
                {% trans 'Upload' %}
            </button>
            <button type="submit" class="btn btn-warning" name="file_delete">
                {% trans 'Delete all cached files' %}
            </button>
        </div>
    </form>
</div>

django_plastic_tickets/templates/plastic_tickets/new_ticket_start.html
{% load i18n %}

<h2>
    {% blocktrans %}
        Ticket creation
    {% endblocktrans %}
</h2>

<p>
    {% blocktrans %}
        Here you can create a new Ticket for 3D models to be 3D printed by us.
    {% endblocktrans %}
</p>

<p>
    {% blocktrans %}
        You will start by adding one or more stl files
        that you want to be printed one or many times.
    {% endblocktrans %}
</p>

<p>
    {% blocktrans %}
        Make sure that you use <b>sane file names</b> as we will reference
        them later.
    {% endblocktrans %}
</p>

<p>
    {% blocktrans %}
        After this you will specify the details about the prints
        and you can add a custom message.
    {% endblocktrans %}
</p>

{% include 'plastic_tickets/new_ticket_file_upload.html' %}

django_plastic_tickets/templates/plastic_tickets/new_ticket_submit.html
{% load i18n %}

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-group">
        <label for="ticket_text">
            {% trans 'Custom message' %}:
        </label>
        <textarea name="ticket_text"
                  id="ticket_text"
                  class="form-text"
                  style="font-family: monospace"
                  rows="5"
                  cols="76"
                  wrap="soft"
                  placeholder="{% trans 'Optional custom message for more details.' %}"></textarea>
    </div>
    <div class="form-group form-check">
        <input type="checkbox" id="send_to_user" name="send_to_user"
               class="form-check-input">
        <label for="send_to_user" class="form-check-label">
            {% trans 'Also send the ticket email to me' %}
        </label>
    </div>
    <div class="form-group">
        <input type="submit" name="create_ticket" class="btn btn-success"
               value="{% trans 'Submit ticket' %}">
    </div>
</form>

django_plastic_tickets/templates/plastic_tickets/overview.html
{% extends 'base.html' %}

{% load i18n %}
{% load django_bootstrap_breadcrumbs %}

{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb 'Plastic tickets' 'plastic_tickets_index' %}
{% endblock %}

{% block content %}
    {{ block.super }}
    {% blocktrans %}
        <h3>Welcome to Plastic Tickets!</h3>
    {% endblocktrans %}

    <br>

    <a href="{% url 'plastic_tickets_new' %}">
        <button class="btn btn-info mb-4" style="min-width: 28ex;">
            {% blocktrans %}
                Click here to create a ticket
            {% endblocktrans %}
        </button>
    </a>
    <br>
    <a href="{% url 'plastic_tickets_list' %}">
        <button class="btn btn-info mb-4" style="min-width: 28ex;">
            {% blocktrans %}
                Manage tickets
            {% endblocktrans %}
        </button>
    </a>
{% endblock %}

django_plastic_tickets/templates/plastic_tickets/ticket_list_view.html
{% extends 'base.html' %}
{% load i18n %}

{% load django_bootstrap_breadcrumbs %}
{% load plastic_extras %}

{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb 'Plastic tickets' 'plastic_tickets_index' %}
    {% breadcrumb 'Manage tickets' 'plastic_tickets_list' %}
{% endblock %}

{% block content %}
<h3>{% trans 'Ticket Overview' %}</h3>

<div style="margin-bottom: 0.3em">
    <span>
        <select class="select2-dropdown" id="select_assignee" name="assignee">
            <option value="__all__"> {% trans 'All assignees' %} </option>
        </select>
    </span>
    {% for state in ticket_states %}
        <span style="background: var(--secondary); border-radius: 0.2em;
padding: 0 1ex 0 1ex; display: flex; align-items: center; float: right;
margin: 0.4em 0 0.4em 0.8em">
            {{ state | ticketbadge }}
&nbsp;
            <input class="form-check-input" type="checkbox" value=""
checked="" style="margin: 0 0 0 5px; position: relative;", id="checkbox_{{state}}"> </input>
        </span>
    {% endfor %}
</div>

<table class="table table-striped">
    <thead>
    <tr>
        <th scope="col"><button type="button" class="btn btn-table-sort" id="id_sort"></button> Ticket</th>
        <th scope="col"><button type="button" class="btn btn-table-sort" id="state_sort"/></button> {% trans 'State' %}</th>
        <th scope="col"><button type="button" class="btn btn-table-sort" id="assignee_sort"/></button> {% trans 'Assignee' %}</th>
    </tr>
    </thead>
    <tbody id="tbody">
    </tbody>
</table>

<script src="/static/javascript/plastic_table.js"></script>

<script type="text/javascript">
    const tickets = {{js_data|safe}};

    function row_builder (row_data, row_ele) {
        var cell = row_ele.insertCell();
        cell.innerHTML = '<a href="/tickets/' + row_data.id + '"># Ticket ' + row_data.id + '</a> '

        cell = row_ele.insertCell();
        if (row_data.state == 'OP') {
            if (row_data.assignee === null) {
                cell.innerHTML = '{{ "UN" | ticketbadge}}';
            } else {
                cell.innerHTML = '{{ "PR" | ticketbadge}}';
            }
        } else if (row_data.state == 'RE') {
            cell.innerHTML = '{{ "RE" | ticketbadge}}';
        } else if (row_data.state == 'DO') {
            cell.innerHTML = '{{ "DO" | ticketbadge}}';
        }

        cell = row_ele.insertCell();
        if (row_data.assignee === null){
            cell.innerHTML = '<em>{% trans "Unassigned" %}</em>'
        } else {
            cell.innerHTML = row_data.assignee;
        }
    }

    let select = document.getElementById('select_assignee');
    select.onchange = () => table.rebuild();

    let table = new PlasticTickets.PlasticTable(tickets, "tbody", row_builder);
    let assignee_list = new Set(tickets.map(row => row.assignee));
    assignee_list.delete(null);
    PlasticTickets.populate_with_options(select, assignee_list);

    ["id", "assignee"].forEach(col => {
        let btn = document.getElementById(col + "_sort");
        let func = (a, b, dir) => PlasticTickets.simple_sort_func(a[col], b[col], dir)
        table.register_sort_button(btn, func);
    });
    const ticket_states = {{ ticket_states|safe }};
    let btn = document.getElementById("state_sort");
    let trans_state = function (row) {
        if(row.state == "OP") {
            if (row.assignee === null) {
                return ticket_states.indexOf("UN");
            } else {
                return ticket_states.indexOf("PR");
            }
        } else {
            return ticket_states.indexOf(row.state);
        }
    }
    let func = (a, b, dir) => PlasticTickets.simple_sort_func(trans_state(a), trans_state(b), dir)
    table.register_sort_button(btn, func);

    {% for state in ticket_states %}
        let checkbox_{{state}} = document.getElementById("checkbox_{{state}}");
        checkbox_{{state}}.onclick = () => table.rebuild();
    {% endfor %}

    table.filter_func = function (row) {
        if (select.value != "__all__" && select.value != row.assignee) {
            return false;
        }
        if (row.state == "DO") {
            return checkbox_DO.checked;
        } else if(row.state == "RE") {
            return checkbox_RE.checked;
        } else if(row.state == "OP") {
            if (row.assignee === null) {
                return checkbox_UN.checked;
            } else {
                return checkbox_PR.checked;
            }
        } else {
            return false;
        }
    }

    table.rebuild();

    window.addEventListener("pageshow", function(event){
        var historyTraversal = event.persisted ||
            (typeof window.performance != "undefined" &&
             window.performance.navigation.type === 2);
        if(historyTraversal){
            window.location.reload();
        }
    });
</script>

{% endblock %}

django_plastic_tickets/templates/plastic_tickets/ticket_view.html
{% extends 'base.html' %}
{% load i18n %}

{% load django_bootstrap_breadcrumbs %}
{% load plastic_extras %}

{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb 'Plastic tickets' 'plastic_tickets_index' %}
    {% breadcrumb 'Manage tickets' 'plastic_tickets_list' %}
    {% breadcrumb ticket.id 'plastic_tickets_ticket' %}
{% endblock %}

{% block content %}
    {% if messages %}
        {% for message in messages %}
            <div {% if message.tags %}
                class="{{ message.tags }}"{% endif %}>{{ message }}</div>
        {% endfor %}
    {% endif %}

    <h3> # Ticket {{ ticket.id }} </h3>

    {{ ticket.badge | ticketbadge }} 
    {% blocktrans with name=user.username email=user.email %}This ticket is from {{ name }} ({{ email }}){% endblocktrans %}
    {% if ticket.assignee %}
        {% blocktrans with name=ticket.assignee.username email=ticket.assignee.email %}and assigned to {{ name }} ({{ email }}){% endblocktrans %}
    {% endif %}

    <br>

    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">{% trans 'File' %}</th>
                <th scope="col">{% trans 'Count' %}</th>
                <th scope="col">{% trans 'Material' %}</th>
                <th scope="col">{% trans 'Color' %}</th>
                {% if request.user.is_staff %}
                    <th scope="col">{% trans 'Labels of possible<br>materials' %}</th>
                {% endif %}
            </tr>
        </thead>
        <tbody>
        {% for config in ticket.printconfig_set.all %}
            <tr>
                <td>
                    <a href="{{ config.get_file_url }}">
                        {{ config.get_file_name }}
                    </a>
                </td>
                <td>{{ config.count }}</td>
                <td>{{ config.get_material_type_name }}</td>
                <td>{{ config.get_color_name }}</td>
                {% if request.user.is_staff %}
                    <td>{{ config.get_material_stock_list }}</td>
                {% endif %}
            </tr>
        {% endfor %}
        </tbody>
    </table>

    {% if ticket.message %}
        <div>
            <label for="message">Message:</label>
            <textarea name="message" id="message"
                      readonly
                      class="form-text"
                      style="font-family: monospace"
                      rows="{{ ticket.get_message_row_count }}"
                      cols="76"
                      wrap="soft">{{ ticket.message }}</textarea>
        </div>
    {% endif %}
    <hr>
    {% if request.user.is_staff %}
        <fieldset>
            <legend>{% trans 'Edit Ticket' %}</legend>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group">
                    <label for="assignee">
                        {% trans 'Assignee' %}
                    </label>
                    <label>
                        <select class="select2-dropdown" id="assignee" name="assignee">
                            <option value="unassigned"> {% trans 'Unassigned' %} </option>
                            {% for user in possible_assignees %}
                                <option value="{{ user.id }}"> {{ user.username }} </option>
                            {% endfor %}
                        </select>
                    </label>
                </div>
                <button type="submit" class="btn btn-primary" id="submit" name="apply">{% trans "Apply Changes" %}</button>
                {% if ticket.state == "OP" %}
                    <button type="submit" class="btn btn-success" name="close">{% trans "Close Ticket" %}</button>
                    <button type="submit" class="btn btn-danger" name="reject">{% trans "Reject Ticket" %}</button>
                {% elif ticket.state == "RE" or ticket.state == "DO" %}
                    <button type="submit" class="btn btn-secondary" name="reopen">{% trans "Reopen Ticket" %}</button>
                {% endif %}
            </form>
        </fieldset>
        <script type="text/javascript">
            window.addEventListener("pageshow", function(event){
                var historyTraversal = event.persisted ||
                    (typeof window.performance != "undefined" &&
                     window.performance.navigation.type === 2);
                if(historyTraversal){
                    window.location.reload();
                }
            });
            let assignee = document.getElementById('assignee');
            {% if ticket.assignee %}
                assignee.value = {{ ticket.assignee.id }};
            {% else %}
                assignee.value = "unassigned";
            {% endif %}
            let submit = document.getElementById('submit');
            assignee.onchange = function () {
            {% if ticket.assignee %}
                    submit.disabled = assignee.value == {{ ticket.assignee.id }};
                {% else %}
                    submit.disabled = assignee.value == "unassigned";
                {% endif %}
            };
            assignee.onchange();
        </script>
    {% endif %}
{% endblock %}